### ISSUE TITLE
Not able to run project

### ISSUE THREAD

**Issue by neerajshukla1911** [gitDanilo/CorpusVR#1]
While trying to run project I am getting following error

LoaderOBJ loaderOBJ = new LoaderOBJ(this, R.raw.lefthand_obj);
		                                               ^
  symbol:   variable lefthand_obj

It seems lefthand_obj is not committed to project. How can I get obj fiile ?

**Comment by gitDanilo** [comment]
Hello.

I used this 3D model here:

https://www.cgtrader.com/3d-models/character/anatomy/human-arm-and-hand-skeletal-bones

If you are planning to use this model for hand tracking (just like in this project), you probably will have to remove some bone parts. Blender is a good choice for that. Also, if you want the 3D model of both hands you can use blender to generate the second model applying -1 scale on all vectors.

Good luck.
